sudo: required
services:
  - docker

before_install:
  - docker build -t  dodo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dodo/react-test npm test -- --coverage

after_success:
  - docker build -t dodo/multi-client ./client
  - docker build -t dodo/multi-nginx ./nginx
  - docker build -t dodo/multi-server ./server
  - docker build -t dodo/mutli-worker ./worker
