version: '3'
services:
  client:
    image: 'dodothedeveloper/multi-client:v2'
    mem_limit: 128m
    hostname: client
  server:
    image: 'dodothedeveloper/multi-server:v2'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'dodothedeveloper/multi-worker:v2'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'dodothedeveloper/multi-nginx:v2'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
